type User {
  id: ID
  loginName: String
  displayName: String
  admin: Boolean
}
type LoginOutput {
  user: User
  accessToken: String
  refreshToken: String
}
input RegisterInput {
  loginName: String!
  displayName: String!
  password: String!
}
type Mutation {
  register(input: RegisterInput): User!
  login(username: String, password: String): LoginOutput!
  token(refreshToken: String): LoginOutput!
}
